name: CI

on:
  push:
    branches: main
  pull_request:
    branches: [main, master]
    types: [opened, reopened, labeled, synchronize]
  workflow_dispatch:
    
permissions:
  pull-requests: read
  contents: read
  issues: read
  
jobs:
  Sonar-Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Data
        uses: actions/checkout@v3
        
      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=Majikjack620_requirements
            -Dsonar.organization=majikjack620
            
  Dependabot-PR-Assigner:
    runs-on: ubuntu-latest
    if: ${{github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Assign PR to Reviewer
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{secrets.TOKENIZED}}
          assignees: Majikjack620
          numOfAssignee: 1
          allowSelfAssign: true
          
  Dependency-Validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Data
        uses: actions/checkout@v3
          
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Check dependencies
        run: |
          pip list --outdated
          pip list --outdated >> dependent.txt
          echo "### :small_red_triangle: OUTDATED/MISSING Dependencies List :small_red_triangle:" >> $GITHUB_STEP_SUMMARY
          python read_file.py >> $GITHUB_STEP_SUMMARY
          echo "##### Update these dependencies to the required version before merging" >> $GITHUB_STEP_SUMMARY
